services:
  mysql:
    image: mysql:latest
    container_name: scrumgame
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DOCKER_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DOCKER_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DOCKER_PORT}
    volumes:
      - ./db/data:/var/lib/mysql
    networks:
      - scrumgame-network
    restart: always

networks:
  scrumgame-network:
    driver: bridge
